from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from app.database import engine, Base
from app.routers import router
from app.services.scheduler import start_scheduler, stop_scheduler
from app.seed import seed_database
import logging
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def ensure_admin():
    from app.database import SessionLocal
    import app.models as models
    from passlib.context import CryptContext
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    db = SessionLocal()
    try:
        admin = db.query(models.User).filter(models.User.email == "admin@cliniquerebecca.ht").first()
        if not admin:
            db.add(models.User(
                email="admin@cliniquerebecca.ht",
                nom="Administrateur",
                hashed_password=pwd_context.hash("rebecca2026"),
                role="admin"
            ))
            db.commit()
            logger.info("✅ Admin créé")
        else:
            # Reset le mot de passe admin au cas où
            admin.hashed_password = pwd_context.hash("rebecca2026")
            admin.role = "admin"
            db.commit()
            logger.info("✅ Admin mot de passe réinitialisé")
    except Exception as e:
        logger.error("Erreur ensure_admin: %s", e)
        db.rollback()
    finally:
        db.close()

def migrate_add_missing_columns():
    """Add new columns and enum values safely without losing data."""
    from sqlalchemy import text
    from app.database import engine

    # ── 1. Convertir colonnes native-enum → VARCHAR (fix critique) ──────────────
    # Le schéma original utilisait Enum(RoleEnum) natif PostgreSQL.
    # Le code actuel utilise native_enum=False (VARCHAR). Cette migration convertit
    # les colonnes existantes pour que les INSERTs fonctionnent sans erreur de type.
    enum_to_varchar = [
        "ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50) USING role::text",
        "ALTER TABLE users ALTER COLUMN type_medecin TYPE VARCHAR(50) USING type_medecin::text",
        "ALTER TABLE rendez_vous ALTER COLUMN statut TYPE VARCHAR(50) USING statut::text",
        "ALTER TABLE rendez_vous ALTER COLUMN type_rdv TYPE VARCHAR(20) USING type_rdv::text",
        "ALTER TABLE rendez_vous ALTER COLUMN devise TYPE VARCHAR(10) USING devise::text",
        "ALTER TABLE dossiers_patients ALTER COLUMN statut TYPE VARCHAR(50) USING statut::text",
        "ALTER TABLE profils_medecins ALTER COLUMN type_medecin TYPE VARCHAR(50) USING type_medecin::text",
        "ALTER TABLE mouvements ALTER COLUMN type TYPE VARCHAR(30) USING type::text",
        "ALTER TABLE mouvements ALTER COLUMN devise TYPE VARCHAR(10) USING devise::text",
        "ALTER TABLE mouvements ALTER COLUMN journal TYPE VARCHAR(10) USING journal::text",
        "ALTER TABLE encaissements ALTER COLUMN devise TYPE VARCHAR(10) USING devise::text",
        "ALTER TABLE decaissements ALTER COLUMN devise TYPE VARCHAR(10) USING devise::text",
        "ALTER TABLE periodes_comptables ALTER COLUMN statut TYPE VARCHAR(20) USING statut::text",
        "ALTER TABLE stocks ALTER COLUMN devise_acquisition TYPE VARCHAR(10) USING devise_acquisition::text",
        "ALTER TABLE tarifs_medecins ALTER COLUMN type_medecin TYPE VARCHAR(50) USING type_medecin::text",
        "ALTER TABLE tarifs_config ALTER COLUMN type_medecin TYPE VARCHAR(50) USING type_medecin::text",
        "ALTER TABLE demandes_acces_dossier ALTER COLUMN statut TYPE VARCHAR(30) USING statut::text",
        "ALTER TABLE labo_analyses ALTER COLUMN type_medecin TYPE VARCHAR(50) USING type_medecin::text",
    ]
    for sql in enum_to_varchar:
        try:
            with engine.connect() as conn:
                conn.execute(text(sql))
                conn.commit()
            print(f"✓ enum→varchar: {sql[35:75]}")
        except Exception as e:
            msg = str(e).lower()
            # "cannot be cast" means it's already varchar — safe to ignore
            if "already exists" not in msg and "cannot be cast" not in msg and "does not exist" not in msg:
                print(f"Enum migration note [{sql[35:55]}]: {e}")

    # ── 2. Ajouter colonnes manquantes ───────────────────────────────────────
    column_migrations = [
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_image TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_updated_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS confirme_par INTEGER",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS confirme_par_role VARCHAR(20)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS autre_moment_propose VARCHAR(50)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS autre_moment_message VARCHAR(500)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS rdv_id INTEGER",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id)",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS categorie VARCHAR(255)",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_usd FLOAT DEFAULT 0",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_usd_min FLOAT",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_usd_max FLOAT",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_clinique_usd FLOAT",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS source_bareme VARCHAR(50)",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_htg_ref FLOAT",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS montant_usd FLOAT",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS montant_usd FLOAT",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS categorie VARCHAR(255)",
        "CREATE TABLE IF NOT EXISTS taux_change (id SERIAL PRIMARY KEY, taux_htg FLOAT NOT NULL, date TIMESTAMP WITH TIME ZONE DEFAULT NOW(), saisi_par INTEGER REFERENCES users(id))",
        "CREATE TABLE IF NOT EXISTS autorisations_paiement (id SERIAL PRIMARY KEY, patient_id INTEGER REFERENCES patients(id), patient_nom VARCHAR(255), patient_numero VARCHAR(20), motif VARCHAR(255), service VARCHAR(255), date_validite TIMESTAMP WITH TIME ZONE, actif BOOLEAN DEFAULT TRUE, created_by INTEGER REFERENCES users(id), created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW())",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS age INTEGER",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS date_naissance DATE",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_profil TEXT",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS photo_profil TEXT",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS contact_urgence VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS is_premiere_visite BOOLEAN DEFAULT TRUE",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS titre VARCHAR(20) DEFAULT \'Dr\'",
        # Tiers comptable (bénéficiaire/payeur)
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS tiers_nom VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS tiers_type VARCHAR(50)",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS tiers_nom VARCHAR(255)",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS solde_compte_468 FLOAT DEFAULT 0",
        # Décaissements planifiés
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS date_prevue TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS statut VARCHAR(20) DEFAULT \'effectue\'",
        # Mouvements enrichis
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS date_mouvement TIMESTAMP WITH TIME ZONE",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS reference VARCHAR(100)",
        # RendezVous — colonnes critiques pour l'enregistrement caissier
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS code_patient VARCHAR(20)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS medecin_email VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS confirme_par INTEGER",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS confirme_par_role VARCHAR(20)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS mouvement_id INTEGER",
        # Autres colonnes critiques
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_image TEXT",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS service VARCHAR(100)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS sexe VARCHAR(10)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS groupe_sanguin VARCHAR(10)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS allergies TEXT",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS antecedents TEXT",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS age INTEGER",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS date_naissance DATE",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS contact_urgence VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS id_papier VARCHAR(50)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS date_premiere_visite TIMESTAMPTZ",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS is_premiere_visite BOOLEAN DEFAULT TRUE",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS categorie VARCHAR(100) DEFAULT \'tous\'",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS type_medecin VARCHAR(50)",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS prix_consultation FLOAT DEFAULT 0",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS prix_rdv FLOAT DEFAULT 0",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS hashed_password VARCHAR(255)",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS telephone VARCHAR(255)",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS type_medecin TEXT",
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT FALSE",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS description TEXT",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS icone VARCHAR(255)",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS couleur VARCHAR(255)",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS ordre INTEGER",
        "ALTER TABLE services ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS description TEXT",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS emoji VARCHAR(255)",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS telephone VARCHAR(255)",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE specialistes ADD COLUMN IF NOT EXISTS ordre INTEGER",
        "ALTER TABLE horaires ADD COLUMN IF NOT EXISTS jour VARCHAR(255)",
        "ALTER TABLE horaires ADD COLUMN IF NOT EXISTS ouvert BOOLEAN DEFAULT FALSE",
        "ALTER TABLE horaires ADD COLUMN IF NOT EXISTS heure_ouverture VARCHAR(255)",
        "ALTER TABLE horaires ADD COLUMN IF NOT EXISTS heure_fermeture VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS numero VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS prenom VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS telephone VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS adresse VARCHAR(255)",
        "ALTER TABLE patients ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS specialiste_id INTEGER",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS patient_telephone VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS patient_email VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS date_rdv TIMESTAMPTZ",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS type_rdv TEXT",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS statut TEXT",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS motif TEXT",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS notes_admin TEXT",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS reference_paiement VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS lien_video VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS numero_rdv VARCHAR(255)",
        "ALTER TABLE rendez_vous ADD COLUMN IF NOT EXISTS rappel_envoye BOOLEAN DEFAULT FALSE",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS numero_piece VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS journal TEXT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS compte_debit VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS compte_credit VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS libelle_debit VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS libelle_credit VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS type TEXT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS categorie VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS description VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS montant_usd FLOAT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS taux_usd_htg FLOAT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS montant_htg FLOAT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS rdv_id INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS periode_mois INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS periode_annee INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS periode_verrou BOOLEAN DEFAULT FALSE",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS est_contrepassation BOOLEAN DEFAULT FALSE",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS mouvement_origine_id INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS tca_applicable BOOLEAN DEFAULT FALSE",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS tca_montant FLOAT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS tca_compte VARCHAR(255)",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS modified_by INTEGER",
        "ALTER TABLE mouvements ADD COLUMN IF NOT EXISTS modified_at TIMESTAMPTZ",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS user_id INTEGER",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS type_medecin TEXT",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS loyer_mensuel_htg FLOAT",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS solde_compte_468 FLOAT",
        "ALTER TABLE profils_medecins ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE regles_partage ADD COLUMN IF NOT EXISTS type_medecin TEXT",
        "ALTER TABLE regles_partage ADD COLUMN IF NOT EXISTS type_acte VARCHAR(255)",
        "ALTER TABLE regles_partage ADD COLUMN IF NOT EXISTS pct_medecin FLOAT",
        "ALTER TABLE regles_partage ADD COLUMN IF NOT EXISTS pct_clinique FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS type_acte VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS description VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS montant_total FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS montant_medecin FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS montant_clinique FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS pct_medecin FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS taux_usd_htg FLOAT",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS balance_ok BOOLEAN DEFAULT FALSE",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS statut_decaissement VARCHAR(255)",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS mouvement_recette_id INTEGER",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS mouvement_honoraires_id INTEGER",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS date_acte TIMESTAMPTZ",
        "ALTER TABLE actes_facturables ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS motif VARCHAR(255)",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS taux_usd_htg FLOAT",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS mouvement_468_id INTEGER",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS mouvement_511_id INTEGER",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS date_decaissement TIMESTAMPTZ",
        "ALTER TABLE decaissements ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE periodes_comptables ADD COLUMN IF NOT EXISTS mois INTEGER",
        "ALTER TABLE periodes_comptables ADD COLUMN IF NOT EXISTS annee INTEGER",
        "ALTER TABLE periodes_comptables ADD COLUMN IF NOT EXISTS statut TEXT",
        "ALTER TABLE periodes_comptables ADD COLUMN IF NOT EXISTS cloture_par INTEGER",
        "ALTER TABLE periodes_comptables ADD COLUMN IF NOT EXISTS cloture_at TIMESTAMPTZ",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS mois INTEGER",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS annee INTEGER",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_consultations FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_gestes FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_chirurgies FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_hospitalisations FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_laboratoire FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_pharmacie FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_loyers_recus FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_autres_produits FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_produits FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_honoraires_medecins FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_salaires FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_charges_sociales FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_pharmacie_achats FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_amortissements FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_infrastructure FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_autres_charges FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_charges FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS resultat_net FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_tca_collectee FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS total_produits_usd FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS taux_usd_moyen FLOAT",
        "ALTER TABLE bilans_mensuels ADD COLUMN IF NOT EXISTS statut VARCHAR(255)",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS libelle VARCHAR(255)",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS compte_pcn VARCHAR(255)",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS valeur_acquisition FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS devise_acquisition TEXT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS taux_usd_achat FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS valeur_htg FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS date_acquisition TIMESTAMPTZ",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS duree_amort_ans INTEGER",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS taux_amort FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS amort_cumule FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS valeur_nette FLOAT",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS date_sortie TIMESTAMPTZ",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS motif_sortie VARCHAR(255)",
        "ALTER TABLE immobilisations ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE tarifs_clinic ADD COLUMN IF NOT EXISTS code VARCHAR(255)",
        "ALTER TABLE tarifs_clinic ADD COLUMN IF NOT EXISTS libelle VARCHAR(255)",
        "ALTER TABLE tarifs_clinic ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE tarifs_clinic ADD COLUMN IF NOT EXISTS unite VARCHAR(255)",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS taux_usd_htg FLOAT",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS flux_direct BOOLEAN DEFAULT FALSE",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS description VARCHAR(255)",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS mouvement_id INTEGER",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS date_paiement TIMESTAMPTZ",
        "ALTER TABLE paiements_exploitants ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS nom VARCHAR(255)",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS categorie VARCHAR(255)",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS quantite INTEGER",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS seuil_min INTEGER",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS prix_unitaire FLOAT",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS devise TEXT",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS unite VARCHAR(255)",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS proprietaire VARCHAR(255)",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS mode_reversement VARCHAR(255)",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS valeur_reversement FLOAT",
        "ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pct_clinique FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS stock_id INTEGER",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS produit_nom VARCHAR(255)",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS quantite INTEGER",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS prix_unitaire FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS montant_total FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS montant_clinique FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS montant_investisseur FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS proprietaire VARCHAR(255)",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS mode_reversement VARCHAR(255)",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255)",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS tca_applicable BOOLEAN DEFAULT FALSE",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS tca_montant FLOAT",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS date_vente TIMESTAMPTZ",
        "ALTER TABLE ventes_pharmacie ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS patient_id VARCHAR(255)",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS type_examen VARCHAR(255)",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS resultats TEXT",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS date_examen TIMESTAMPTZ",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS technicien_id INTEGER",
        "ALTER TABLE resultats_labo ADD COLUMN IF NOT EXISTS status VARCHAR(255)",
        "ALTER TABLE contrat_optometrie ADD COLUMN IF NOT EXISTS pct_consultation FLOAT",
        "ALTER TABLE contrat_optometrie ADD COLUMN IF NOT EXISTS pct_montures FLOAT",
        "ALTER TABLE contrat_optometrie ADD COLUMN IF NOT EXISTS minimum_mensuel_usd FLOAT",
        "ALTER TABLE contrat_optometrie ADD COLUMN IF NOT EXISTS taux_usd_htg FLOAT",
        "ALTER TABLE contrat_optometrie ADD COLUMN IF NOT EXISTS updated_by INTEGER",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS code VARCHAR(255)",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS libelle VARCHAR(255)",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS devise VARCHAR(255)",
        "ALTER TABLE tarifs_labo ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS code VARCHAR(255)",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS libelle VARCHAR(255)",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS montant FLOAT",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS devise VARCHAR(255)",
        "ALTER TABLE tarifs_dentiste ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS specialiste_id INTEGER",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS prix_hospitalisation_jr FLOAT",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS prix_geste_base FLOAT",
        "ALTER TABLE tarifs_medecins ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS libelle VARCHAR(255)",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS prix_fixe BOOLEAN DEFAULT FALSE",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE gestes_medicaux ADD COLUMN IF NOT EXISTS ordre INTEGER",
        "ALTER TABLE taux_change ADD COLUMN IF NOT EXISTS taux_htg FLOAT",
        "ALTER TABLE taux_change ADD COLUMN IF NOT EXISTS date TIMESTAMPTZ",
        "ALTER TABLE taux_change ADD COLUMN IF NOT EXISTS saisi_par INTEGER",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS mois INTEGER",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS annee INTEGER",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS total_consultations FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS total_montures FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS part_clinique_consultations FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS part_clinique_montures FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS total_part_clinique FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS minimum_applicable_htg FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS montant_final_clinique FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS difference FLOAT",
        "ALTER TABLE bilans_optometrie ADD COLUMN IF NOT EXISTS statut VARCHAR(255)",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS medecin_specialite VARCHAR(255)",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS patient_numero VARCHAR(255)",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS motif TEXT",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS urgence BOOLEAN DEFAULT FALSE",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS statut TEXT",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS admin_id INTEGER",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS admin_commentaire TEXT",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS duree_acces_h INTEGER",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS acces_expire_at TIMESTAMPTZ",
        "ALTER TABLE demandes_acces_dossier ADD COLUMN IF NOT EXISTS decided_at TIMESTAMPTZ",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS audit_id VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS event_type VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_id INTEGER",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_role VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_id VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_type VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS device_info VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS session_id VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS result VARCHAR(255)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details TEXT",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS retention_ans INTEGER",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS patient_nom VARCHAR(255)",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS patient_numero VARCHAR(255)",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS motif VARCHAR(255)",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS service VARCHAR(255)",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS date_validite TIMESTAMPTZ",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS actif BOOLEAN DEFAULT FALSE",
        "ALTER TABLE autorisations_paiement ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS patient_numero VARCHAR(255)",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS infirmier_id INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS type_visite VARCHAR(255)",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS service VARCHAR(255)",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS specialite VARCHAR(255)",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS statut TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS paiement_effectue BOOLEAN DEFAULT FALSE",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS mouvement_paiement_id INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS locked BOOLEAN DEFAULT FALSE",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS unlock_par INTEGER",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS unlock_at TIMESTAMPTZ",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS motif_consultation TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS anamnese TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS examen_clinique TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS diagnostic TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS notes_medecin TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS synthese_ia TEXT",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS date_visite TIMESTAMPTZ",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS date_fin_consultation TIMESTAMPTZ",
        "ALTER TABLE dossiers_patients ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS tension_systolique FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS tension_diastolique FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS frequence_cardiaque INTEGER",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS temperature FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS frequence_respiratoire INTEGER",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS saturation_o2 FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS poids FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS taille FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS glycemie FLOAT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS alerte_critique BOOLEAN DEFAULT FALSE",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS alerte_message TEXT",
        "ALTER TABLE signes_vitaux ADD COLUMN IF NOT EXISTS saisi_par INTEGER",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS medicaments TEXT",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS examens_requis TEXT",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS notes TEXT",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS signature_hash VARCHAR(255)",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS signee BOOLEAN DEFAULT FALSE",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS date_prescription TIMESTAMPTZ",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS valide_jusqu_au TIMESTAMPTZ",
        "ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS statut VARCHAR(255)",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS patient_numero VARCHAR(255)",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS priorite INTEGER",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS statut VARCHAR(255)",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS heure_entree TIMESTAMPTZ",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS heure_appel TIMESTAMPTZ",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS heure_fin TIMESTAMPTZ",
        "ALTER TABLE file_attente ADD COLUMN IF NOT EXISTS place_par INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS patient_numero VARCHAR(255)",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS type_sejour VARCHAR(255)",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS medecin_id INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS lit_numero VARCHAR(255)",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS service VARCHAR(255)",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS date_admission TIMESTAMPTZ",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS date_sortie TIMESTAMPTZ",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS nb_jours INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS tarif_journalier FLOAT",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS total_hebergement FLOAT",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS acquittement_total BOOLEAN DEFAULT FALSE",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS mouvement_id INTEGER",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS statut VARCHAR(255)",
        "ALTER TABLE hospitalisations ADD COLUMN IF NOT EXISTS created_by INTEGER",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS patient_id INTEGER",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS dossier_id INTEGER",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS medecin_nom VARCHAR(255)",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS service VARCHAR(255)",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS note INTEGER",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS commentaire TEXT",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS sentiment_ia VARCHAR(255)",
        "ALTER TABLE avis_patients ADD COLUMN IF NOT EXISTS anonyme BOOLEAN DEFAULT FALSE",
        "ALTER TABLE liens_video_rdv ADD COLUMN IF NOT EXISTS rdv_id INTEGER",
        "ALTER TABLE liens_video_rdv ADD COLUMN IF NOT EXISTS token_jwt VARCHAR(255)",
        "ALTER TABLE liens_video_rdv ADD COLUMN IF NOT EXISTS lien_video VARCHAR(255)",
        "ALTER TABLE liens_video_rdv ADD COLUMN IF NOT EXISTS expire_at TIMESTAMPTZ",
        "ALTER TABLE liens_video_rdv ADD COLUMN IF NOT EXISTS utilise BOOLEAN DEFAULT FALSE",
    ]
    # Each migration in its own connection to avoid transaction interference
    for sql in column_migrations:
        try:
            with engine.connect() as conn:
                conn.execute(text(sql))
                conn.commit()
            print(f"✓ {sql[:70]}")
        except Exception as e:
            msg = str(e).lower()
            if "already exists" not in msg and "duplicate" not in msg:
                print(f"Migration warning [{sql[:40]}]: {e}")

@asynccontextmanager
async def lifespan(app: FastAPI):
    Base.metadata.create_all(bind=engine)
    migrate_add_missing_columns()
    seed_database()
    ensure_admin()
    start_scheduler()
    yield
    stop_scheduler()

# FORCE_REDEPLOY_2026-05-08
app = FastAPI(title="Clinique de la Rebecca API", version="1.0.0", lifespan=lifespan, docs_url="/docs", redoc_url=None)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/api")

@app.get("/")
async def root():
    return {"status": "ok"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
