"""
seed_data.py — Données réelles de la Clinique de la Rebecca
Importées depuis BD.xlsx et BDM.xlsx
"""

# ── MÉDECINS avec leurs prix individuels ─────────────────────────────────────
MEDECINS = [
    {"nom": "Dr Peterly PHILIPPE",       "specialite": "Orthopédie",                    "telephone": "3780-4789", "prix_consultation": 6500, "prix_rdv": 6500, "type_medecin": "investisseur"},
    {"nom": "Dr Wisly Joseph",           "specialite": "Chirurgie Générale",             "telephone": "3865-5254", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Jean Berldine",          "specialite": "Chirurgie Générale",             "telephone": "3685-7346", "prix_consultation": 4000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Mikerline Charles",      "specialite": "Pédiatrie",                      "telephone": "3673-8631", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Bernard Pierre",         "specialite": "Neurochirurgie",                 "telephone": "3719-2362", "prix_consultation": 5000, "prix_rdv": 5000, "type_medecin": "investisseur"},
    {"nom": "Dr Pierre Billy Lemaus",    "specialite": "Urologie",                       "telephone": "3663-8503", "prix_consultation": 5000, "prix_rdv": 4000, "type_medecin": "investisseur"},
    {"nom": "Dr Eliode Pierre",          "specialite": "Gynécologie",                    "telephone": "3774-9416", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Marie Kerline Pierre",   "specialite": "Anesthésiologie / Réanimation",  "telephone": "3780-6951", "prix_consultation": 5000, "prix_rdv": 5000, "type_medecin": "investisseur"},
    {"nom": "Dr Brunot Simon",           "specialite": "Orthopédie",                     "telephone": "3889-3720", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Vania Louissaint",       "specialite": "Médecine interne",               "telephone": "4217-8031", "prix_consultation": 5000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Jeff Tesnor",            "specialite": "Chirurgie Générale",             "telephone": "3459-4612", "prix_consultation": 6000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Delvalès Doccy",         "specialite": "Gynécologie",                    "telephone": "3493-6533", "prix_consultation": 5000, "prix_rdv": 4000, "type_medecin": "investisseur"},
    {"nom": "Dr Bob-Hallen Treisma",     "specialite": "Gynécologie",                    "telephone": "3816-5368", "prix_consultation": 5000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Jenh Robert",            "specialite": "Chirurgie Pédiatrique",          "telephone": "3406-0998", "prix_consultation": 5000, "prix_rdv": 5000, "type_medecin": "investisseur"},
    {"nom": "Dr Duvivier",               "specialite": "Pédiatrie",                      "telephone": "3325-9190", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Sophie Beaujour",        "specialite": "Dermatologie",                   "telephone": "3294-3481", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "investisseur"},
    {"nom": "Dr Jean Daniel",            "specialite": "Gynécologie",                    "telephone": "3634-3265", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "affilie"},
    {"nom": "Dr Clifford Edouard",       "specialite": "Orthopédie",                     "telephone": "3327-3689", "prix_consultation": 4000, "prix_rdv": 3000, "type_medecin": "affilie"},
    {"nom": "Dr Christelle Philippe",    "specialite": "Médecine interne",               "telephone": "3894-8400", "prix_consultation": 4000, "prix_rdv": 3000, "type_medecin": "affilie"},
    {"nom": "Dr Rose Stephanie Joseph",  "specialite": "Pédiatrie",                      "telephone": "3614-4332", "prix_consultation": 3500, "prix_rdv": 3500, "type_medecin": "affilie"},
    {"nom": "Dr Kaina Michaud",          "specialite": "ORL",                            "telephone": "3891-1659", "prix_consultation": 4000, "prix_rdv": 4000, "type_medecin": "affilie"},
    {"nom": "Dr Lemoine Lafleur",        "specialite": "Neurologie",                     "telephone": "4869-0495", "prix_consultation": 6000, "prix_rdv": 5000, "type_medecin": "investisseur"},
    {"nom": "Dr Auguste Samy",           "specialite": "Orthopédie",                     "telephone": "3833-2358", "prix_consultation": 4500, "prix_rdv": 4000, "type_medecin": "investisseur"},
    {"nom": "Dr Enold Lubin",            "specialite": "Gynécologie",                    "telephone": "4853-4651", "prix_consultation": 4000, "prix_rdv": 3000, "type_medecin": "affilie"},
    {"nom": "Dr Dauphin Roolandro",      "specialite": "Gynécologie",                    "telephone": "3106-4936", "prix_consultation": 2000, "prix_rdv": 2000, "type_medecin": "affilie"},
    {"nom": "Dr Wolf Charlie Cajuste",   "specialite": "Dentisterie",                    "telephone": "3810-7562", "prix_consultation": 2500, "prix_rdv": 2500, "type_medecin": "exploitant"},
    {"nom": "Mme Fredia Fleurival",      "specialite": "Physiothérapie",                 "telephone": "3368-8796", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "exploitant"},
    {"nom": "Dr Gilles Abraham",         "specialite": "Optométrie",                     "telephone": "3627-1021", "prix_consultation": 2000, "prix_rdv": 2000, "type_medecin": "exploitant"},
    {"nom": "Mr Reginald Volcy",         "specialite": "Psychologie",                    "telephone": "4308-9457", "prix_consultation": 3000, "prix_rdv": 3000, "type_medecin": "affilie"},
    {"nom": "Dr Jean Luc Mathurin",      "specialite": "Radiologie",                     "telephone": "4007-6328", "prix_consultation": 0,    "prix_rdv": 0,    "type_medecin": "exploitant"},
]

# ── TARIFS DENTISTERIE ────────────────────────────────────────────────────────
TARIFS_DENTISTE = [
    # Soins de base (HTG)
    {"code": "DENT_CONS",   "libelle": "Consultation",                          "montant": 2500,  "devise": "HTG"},
    {"code": "DENT_REST_P", "libelle": "Restauration dents postérieures",        "montant": 4000,  "devise": "HTG"},
    {"code": "DENT_REST_A", "libelle": "Restauration dents antérieures",         "montant": 4500,  "devise": "HTG"},
    {"code": "DENT_EXTR_S", "libelle": "Extraction simple",                      "montant": 5000,  "devise": "HTG"},
    {"code": "DENT_PROPH1", "libelle": "Prophylaxie simple (grade 1)",            "montant": 7500,  "devise": "HTG"},
    {"code": "DENT_PROPH2", "libelle": "Prophylaxie (grade 2)",                  "montant": 15000, "devise": "HTG"},
    {"code": "DENT_PROPH3", "libelle": "Prophylaxie (grade 3)",                  "montant": 30000, "devise": "HTG"},
    {"code": "DENT_PROPH4", "libelle": "Prophylaxie (grade 4)",                  "montant": 37500, "devise": "HTG"},
    {"code": "DENT_EXTR_SI","libelle": "Extraction semi-incluse",                 "montant": 35000, "devise": "HTG"},
    {"code": "DENT_EXTR_I", "libelle": "Extraction incluse",                     "montant": 50000, "devise": "HTG"},
    {"code": "DENT_RADIO",  "libelle": "Radiographie dentaire",                  "montant": 1500,  "devise": "HTG"},
    {"code": "DENT_ENDO_A", "libelle": "Dévitalisation dent antérieure",          "montant": 20000, "devise": "HTG"},
    {"code": "DENT_ENDO_PM","libelle": "Dévitalisation prémolaire",              "montant": 30000, "devise": "HTG"},
    {"code": "DENT_ENDO_P", "libelle": "Dévitalisation dent postérieure",         "montant": 50000, "devise": "HTG"},
    {"code": "DENT_DECAP",  "libelle": "Décapuchonnage",                         "montant": 5000,  "devise": "HTG"},
    {"code": "DENT_EPULIS", "libelle": "Exérèse épulis",                         "montant": 20000, "devise": "HTG"},
    {"code": "DENT_DESINST","libelle": "Désinstallation bagues",                 "montant": 10000, "devise": "HTG"},
    # USD
    {"code": "DENT_COR_P",  "libelle": "Couronne porcelaine",                    "montant": 500,   "devise": "USD"},
    {"code": "DENT_COR_Z",  "libelle": "Couronne zirconium",                     "montant": 600,   "devise": "USD"},
    {"code": "DENT_PONT_P", "libelle": "Pont porcelaine (par pièce)",             "montant": 500,   "devise": "USD"},
    {"code": "DENT_PONT_Z", "libelle": "Pont zirconium (par pièce)",              "montant": 600,   "devise": "USD"},
    {"code": "DENT_BRACE",  "libelle": "Bagues (Braces) — selon cas",            "montant": 200,   "devise": "USD"},
    {"code": "DENT_ELAST",  "libelle": "Changement élastique + Prophylaxie",     "montant": 50,    "devise": "USD"},
    {"code": "DENT_RETENU", "libelle": "Reteneur",                               "montant": 150,   "devise": "USD"},
    {"code": "DENT_EXPAND", "libelle": "Expender (enfant)",                      "montant": 200,   "devise": "USD"},
    {"code": "DENT_PROT_T", "libelle": "Prothèse totale sup. et inf.",            "montant": 0,     "devise": "HTG"},  # Variable
    {"code": "DENT_CONTEN", "libelle": "Contention en parodontologie",           "montant": 5000,  "devise": "HTG"},
]

# ── TARIFS LABORATOIRE (Liste complète Février 2026) ─────────────────────────
TARIFS_LABO = [
    {"code": "LABO_ACIDE_FOL",    "libelle": "Acide Folique (B9)",                     "montant": 2900},
    {"code": "LABO_ACIDE_UR",     "libelle": "Acide Urique",                           "montant": 1250},
    {"code": "LABO_ACIDE_URU",    "libelle": "Acide Urique Urinaire",                  "montant": 1250},
    {"code": "LABO_ACTH",         "libelle": "ACTH",                                   "montant": 3000},
    {"code": "LABO_AFP_GEST",     "libelle": "AFP/Gestation",                          "montant": 2900},
    {"code": "LABO_ALBUMINE",     "libelle": "Albumine",                               "montant": 900},
    {"code": "LABO_ALPHA_AFP",    "libelle": "Alpha Foeto-Protéine (AFP)",              "montant": 2900},
    {"code": "LABO_AMYLASE",      "libelle": "Amylase",                                "montant": 900},
    {"code": "LABO_AMYLASE_U",    "libelle": "Amylase Urinaire",                       "montant": 900},
    {"code": "LABO_ANA",          "libelle": "ANA",                                    "montant": 1600},
    {"code": "LABO_ANDROST",      "libelle": "Androsténedione",                        "montant": 1700},
    {"code": "LABO_ANTI_CCP",     "libelle": "Anti CCP",                               "montant": 2600},
    {"code": "LABO_ANTI_DNA",     "libelle": "Anti DNA",                               "montant": 2100},
    {"code": "LABO_ANTI_HBC",     "libelle": "Anti HBC",                               "montant": 1600},
    {"code": "LABO_ANTI_HBC_IGG", "libelle": "Anti HBC/IgG",                          "montant": 1600},
    {"code": "LABO_ANTI_HBE",     "libelle": "Anti HBE",                               "montant": 1600},
    {"code": "LABO_ANTI_HBS",     "libelle": "Anti HBS",                               "montant": 1600},
    {"code": "LABO_ANTI_MPO",     "libelle": "Anti MPO (P-ANKA)",                      "montant": 1600},
    {"code": "LABO_ANTI_MUL",     "libelle": "Anti Mullerian H",                       "montant": 2900},
    {"code": "LABO_ANTI_PR3",     "libelle": "Anti PR3 (C-ANKA)",                      "montant": 1600},
    {"code": "LABO_ANTI_MICRO",   "libelle": "Anticorps Antimicrosome",                "montant": 2100},
    {"code": "LABO_ANTI_THYRO",   "libelle": "Anticorps Antithyroglobuline",           "montant": 2100},
    {"code": "LABO_ANTIG_CHLAM",  "libelle": "Antigène Chlamydia",                     "montant": 2900},
    {"code": "LABO_ANTIG_GIAR",   "libelle": "Antigène Giardia Lamblia",               "montant": 1700},
    {"code": "LABO_ANTIG_HBE",    "libelle": "Antigène HBE",                           "montant": 1600},
    {"code": "LABO_ANTIG_MAL",    "libelle": "Antigène Malarique",                     "montant": 900},
    {"code": "LABO_ANTIG_PSA_L",  "libelle": "Antigène Prostatique Libre",             "montant": 3400},
    {"code": "LABO_ANTIG_PSA_S",  "libelle": "Antigène Prostatique Spécifique (PSA)",  "montant": 2600},
    {"code": "LABO_ANTI_TPO",     "libelle": "Anti-Thyroid Proxidase",                 "montant": 2150},
    {"code": "LABO_ASO",          "libelle": "ASO",                                    "montant": 1000},
    {"code": "LABO_ATOUT1",       "libelle": "Atout 1",                                "montant": 700},
    {"code": "LABO_ATOUT2",       "libelle": "Atout 2",                                "montant": 900},
    {"code": "LABO_ATOUT3",       "libelle": "Atout 3",                                "montant": 1900},
    {"code": "LABO_ATOUT4",       "libelle": "Atout 4",                                "montant": 3900},
    {"code": "LABO_ATOUT5",       "libelle": "Atout 5",                                "montant": 15900},
    {"code": "LABO_ATOUT6",       "libelle": "Atout 6",                                "montant": 7900},
    {"code": "LABO_AZOTE_UREE",   "libelle": "Azote de l'Urée",                        "montant": 900},
    {"code": "LABO_B2_MICRO",     "libelle": "B2 Microglobuline",                      "montant": 1600},
    {"code": "LABO_BHCG",         "libelle": "BHCG",                                   "montant": 1100},
    {"code": "LABO_BHCG_QUANT",   "libelle": "BHCG Quantitatif",                       "montant": 2100},
    {"code": "LABO_BIL_COAG",     "libelle": "Bilan Coagulation",                      "montant": 2900},
    {"code": "LABO_BIL_HORM",     "libelle": "Bilan Hormonal",                         "montant": 7100},
    {"code": "LABO_BIL_HRT",      "libelle": "Bilan HRT",                              "montant": 5500},
    {"code": "LABO_BIL_LIPID",    "libelle": "Bilan Lipidique",                        "montant": 2500},
    {"code": "LABO_BIL_RENAL",    "libelle": "Bilan Rénal",                            "montant": 1500},
    {"code": "LABO_BIL_SAT",      "libelle": "Bilan Thérapeutique Saturation Transférine", "montant": 1400},
    {"code": "LABO_BILIRUB",      "libelle": "Bilirubine",                              "montant": 900},
    {"code": "LABO_BLEU_METH",    "libelle": "Bleu de Méthylène",                      "montant": 700},
    {"code": "LABO_CA125",        "libelle": "CA 125",                                  "montant": 2600},
    {"code": "LABO_CA153",        "libelle": "CA 15-3",                                 "montant": 2600},
    {"code": "LABO_CA199",        "libelle": "CA 19-9",                                 "montant": 2900},
    {"code": "LABO_CALCIUM",      "libelle": "Calcium",                                "montant": 900},
    {"code": "LABO_CALCIUM_U",    "libelle": "Calcium Urinaire",                       "montant": 1400},
    {"code": "LABO_CALPROT",      "libelle": "Calprotectine Fécale",                   "montant": 4400},
    {"code": "LABO_CARBAMAZ",     "libelle": "Carbamazépine",                          "montant": 1600},
    {"code": "LABO_CEA",          "libelle": "CEA",                                    "montant": 2600},
    {"code": "LABO_CELLULE_LE",   "libelle": "Cellule LE",                             "montant": 900},
    {"code": "LABO_CHIKUNG",      "libelle": "Chikungunya IgM",                        "montant": 3400},
    {"code": "LABO_CHIMIE_S",     "libelle": "Chimie Sanguine",                        "montant": 3100},
    {"code": "LABO_CHLAM_IGG",    "libelle": "Chlamydia IgG",                          "montant": 2600},
    {"code": "LABO_CHLORURE",     "libelle": "Chlorure",                               "montant": 900},
    {"code": "LABO_CHLORURE_U",   "libelle": "Chlorure Urinaire",                      "montant": 900},
    {"code": "LABO_CHOLEST",      "libelle": "Cholestérol",                            "montant": 900},
    {"code": "LABO_CK_MB",        "libelle": "CK-MB (enzyme Cardiaque)",               "montant": 2600},
    {"code": "LABO_CLEAR_CREAT",  "libelle": "Clearance de la Créatinine",             "montant": 1600},
    {"code": "LABO_CMV_IGG",      "libelle": "CMV IgG",                                "montant": 2600},
    {"code": "LABO_COCAINE",      "libelle": "Cocaïne",                                "montant": 1600},
    {"code": "LABO_COLORA_BK",    "libelle": "Coloration BK",                         "montant": 900},
    {"code": "LABO_CONC",         "libelle": "Concentration",                          "montant": 700},
    {"code": "LABO_COOMBS_D",     "libelle": "Coombs Direct",                         "montant": 1400},
    {"code": "LABO_COOMBS_I",     "libelle": "Coombs Indirect",                       "montant": 1400},
    {"code": "LABO_CORTISOL_AM",  "libelle": "Cortisol AM",                           "montant": 1600},
    {"code": "LABO_CORTISOL_PM",  "libelle": "Cortisol PM",                           "montant": 1600},
    {"code": "LABO_CORTISOL_U",   "libelle": "Cortisol Urinaire",                     "montant": 2600},
    {"code": "LABO_COTININE",     "libelle": "Cotinine",                               "montant": 1400},
    {"code": "LABO_COVID19",      "libelle": "COVID 19",                               "montant": 5900},
    {"code": "LABO_C_PEPTIDE",    "libelle": "C-Peptide",                              "montant": 2600},
    {"code": "LABO_C_PEPTIDE_2H", "libelle": "C-Peptide 2 Heures",                    "montant": 2600},
    {"code": "LABO_CPK",          "libelle": "CPK",                                    "montant": 900},
    {"code": "LABO_CRACHATS_S",   "libelle": "Crachats en Série",                     "montant": 1600},
    {"code": "LABO_CRP",          "libelle": "C-Réactive Protéine (CRP)",              "montant": 1100},
    {"code": "LABO_CREAT",        "libelle": "Créatinine",                             "montant": 1100},
    {"code": "LABO_CREAT_U",      "libelle": "Créatinine Urinaire",                   "montant": 1600},
    {"code": "LABO_CROSSMATCH",   "libelle": "Crossmatch",                             "montant": 900},
    {"code": "LABO_CRP_HS",       "libelle": "CRP High Sensitivity",                  "montant": 2100},
    {"code": "LABO_CRYPTOSP",     "libelle": "Cryptosporidium",                        "montant": 900},
    {"code": "LABO_CULT_EAU",     "libelle": "Culture de l'Eau",                      "montant": 900},
    {"code": "LABO_CULT_CRAC",    "libelle": "Culture des Crachats",                  "montant": 1600},
    {"code": "LABO_CULT_SELL",    "libelle": "Culture des Selles",                    "montant": 1600},
    {"code": "LABO_CULT_URIN",    "libelle": "Culture des Urines",                    "montant": 1600},
    {"code": "LABO_CULT_LIQ",     "libelle": "Culture du Liquide",                    "montant": 1600},
    {"code": "LABO_CULT_SPER",    "libelle": "Culture du Sperme",                     "montant": 1600},
    {"code": "LABO_CULT_PUS",     "libelle": "Culture Pus",                           "montant": 1600},
    {"code": "LABO_CULT_PHAR",    "libelle": "Culture Sec. Pharyngées",               "montant": 1600},
    {"code": "LABO_CULT_COL",     "libelle": "Culture Sec. Col Utérus",               "montant": 1600},
    {"code": "LABO_CULT_OEIL",    "libelle": "Culture Sec. de l'Oeil",                "montant": 1700},
    {"code": "LABO_CULT_GORGE",   "libelle": "Culture Sec. Gorge",                    "montant": 1600},
    {"code": "LABO_CULT_NASAL",   "libelle": "Culture Sec. Nasales",                  "montant": 1600},
    {"code": "LABO_CULT_OR_D",    "libelle": "Culture Sec. Oreille Droite",           "montant": 1600},
    {"code": "LABO_CULT_OR_G",    "libelle": "Culture Sec. Oreille Gauche",           "montant": 1600},
    {"code": "LABO_CULT_CERV",    "libelle": "Culture Sec. Cervicales",               "montant": 1600},
    {"code": "LABO_CULT_URETH",   "libelle": "Culture Sec. Urétrales",                "montant": 1600},
    {"code": "LABO_CULT_VAG",     "libelle": "Culture Sec. Vaginales",                "montant": 1600},
    {"code": "LABO_CULT_SECR",    "libelle": "Culture Sécrétions",                    "montant": 1600},
    {"code": "LABO_CULT_SELL_S",  "libelle": "Culture Selles en Série",               "montant": 3800},
    {"code": "LABO_D_DIMERE",     "libelle": "D-Dimère",                              "montant": 6000},
    {"code": "LABO_D_DIMERE_Q",   "libelle": "D-Dimère Quantitatif",                  "montant": 6000},
    {"code": "LABO_DENGUE",       "libelle": "Dengue",                                "montant": 1600},
    {"code": "LABO_DEPLACE1",     "libelle": "Déplacement 1",                         "montant": 900},
    {"code": "LABO_DEPLACE2",     "libelle": "Déplacement 2",                         "montant": 1700},
    {"code": "LABO_DHEAS",        "libelle": "DHEAS",                                  "montant": 1600},
    {"code": "LABO_DIGOXIN",      "libelle": "Digoxin",                               "montant": 1600},
    {"code": "LABO_DILANTIN",     "libelle": "Dilantin / Phénytoïne",                 "montant": 1600},
    {"code": "LABO_CO2",          "libelle": "Dioxyde de Carbone (CO2)",              "montant": 900},
    {"code": "LABO_DRUG_AP",      "libelle": "Drug Abuse Panel",                      "montant": 5900},
    {"code": "LABO_DRUG_AP2",     "libelle": "Drug Abuse Panel II",                   "montant": 2900},
    {"code": "LABO_DRUG_P1",      "libelle": "Drug Panel I",                          "montant": 2400},
    {"code": "LABO_ELECTROL",     "libelle": "Électrolytes",                          "montant": 2100},
    {"code": "LABO_ELECTRO_HB",   "libelle": "Électrophorèse / Hémoglobine",          "montant": 1500},
    {"code": "LABO_ELECTRO_PROT", "libelle": "Électrophorèse des Protéines",          "montant": 1600},
    {"code": "LABO_EOSINOPH",     "libelle": "Éosinophiles",                          "montant": 600},
    {"code": "LABO_EPSTEIN_M",    "libelle": "Epstein Baar M",                        "montant": 1700},
    {"code": "LABO_ESTRADIOL",    "libelle": "Estradiol",                             "montant": 1600},
    {"code": "LABO_FACT_RHUM",    "libelle": "Facteur Rhumatoïde",                   "montant": 1500},
    {"code": "LABO_FER",          "libelle": "Fer Sérique",                           "montant": 1300},
    {"code": "LABO_FERRIT",       "libelle": "Ferritine",                             "montant": 1400},
    {"code": "LABO_FIBRIN",       "libelle": "Fibrinogène",                           "montant": 900},
    {"code": "LABO_FROTTIS_C",    "libelle": "Frottis Cervical",                      "montant": 1000},
    {"code": "LABO_FROTTIS_G",    "libelle": "Frottis Gorge",                         "montant": 1000},
    {"code": "LABO_FROTTIS_GR",   "libelle": "Frottis Gram",                          "montant": 1000},
    {"code": "LABO_FROTTIS_N",    "libelle": "Frottis Nasal",                         "montant": 1000},
    {"code": "LABO_FROTTIS_OE",   "libelle": "Frottis Oeil",                          "montant": 1000},
    {"code": "LABO_FROTTIS_OR",   "libelle": "Frottis Oreille",                       "montant": 1000},
    {"code": "LABO_FROTTIS_P",    "libelle": "Frottis Pus",                           "montant": 1000},
    {"code": "LABO_FROTTIS_U",    "libelle": "Frottis Urethral",                      "montant": 1000},
    {"code": "LABO_FROTTIS_V",    "libelle": "Frottis Vaginal / Gtte Pendante",       "montant": 1000},
    {"code": "LABO_FSH",          "libelle": "FSH",                                   "montant": 1600},
    {"code": "LABO_G6PD",         "libelle": "G6PD",                                  "montant": 1750},
    {"code": "LABO_GAMMA_GT",     "libelle": "Gamma GT",                              "montant": 1100},
    {"code": "LABO_GLUC_TOL",     "libelle": "Glucose Tolérance Test",                "montant": 2900},
    {"code": "LABO_GLYC_0.5H",    "libelle": "Glycémie 1/2 Heure",                   "montant": 900},
    {"code": "LABO_GLYC_1H",      "libelle": "Glycémie 1 Heure",                     "montant": 900},
    {"code": "LABO_GLYC_2H",      "libelle": "Glycémie 2 Heures",                    "montant": 900},
    {"code": "LABO_GLYC_3H",      "libelle": "Glycémie 3 Heures",                    "montant": 900},
    {"code": "LABO_GLYC_4H",      "libelle": "Glycémie 4 Heures",                    "montant": 900},
    {"code": "LABO_GLYC_JEUN",    "libelle": "Glycémie à Jeun",                      "montant": 900},
    {"code": "LABO_GOUTTE_P",     "libelle": "Goutte Pendante",                       "montant": 900},
    {"code": "LABO_GRIPPE",       "libelle": "Grippe",                                "montant": 4400},
    {"code": "LABO_HBEAG",        "libelle": "HBeAg",                                 "montant": 1400},
    {"code": "LABO_HDL",          "libelle": "HDL",                                   "montant": 900},
    {"code": "LABO_HELICO_S",     "libelle": "Helicobacter Pylori / Selles",          "montant": 1900},
    {"code": "LABO_HELICO_SR",    "libelle": "Helicobacter Pylori / Sérum",           "montant": 1400},
    {"code": "LABO_HEMOCU",       "libelle": "Hémoculture",                           "montant": 1700},
    {"code": "LABO_HBA1C",        "libelle": "Hémoglobine Glyquée (HBA1C)",          "montant": 2000},
    {"code": "LABO_HEMOG_C",      "libelle": "Hémogramme Complet",                   "montant": 1000},
    {"code": "LABO_HEMOG_A",      "libelle": "Hémogramme abs",                       "montant": 1500},
    {"code": "LABO_HEP_A_IGG",    "libelle": "Hépatite A IgG",                       "montant": 1600},
    {"code": "LABO_HEP_A_IGM",    "libelle": "Hépatite A IgM",                       "montant": 1600},
    {"code": "LABO_HEP_B",        "libelle": "Hépatite B",                            "montant": 1400},
    {"code": "LABO_HEP_C",        "libelle": "Hépatite C",                            "montant": 1400},
    {"code": "LABO_HERPES_IGG",   "libelle": "Herpès 2 IgG",                         "montant": 2600},
    {"code": "LABO_HIV_CONF",     "libelle": "HIV Confirmation",                      "montant": 1500},
    {"code": "LABO_HIV_SCR",      "libelle": "HIV Screening",                         "montant": 1000},
    {"code": "LABO_HOMOCYST",     "libelle": "Homocystéine",                          "montant": 3900},
    {"code": "LABO_HORM_CROIS",   "libelle": "Hormone de Croissance",                 "montant": 1700},
    {"code": "LABO_HYDROXY",      "libelle": "Hydroxycorticostéroïdes 17",            "montant": 2600},
    {"code": "LABO_INS_1H",       "libelle": "Insuline 1 Heure",                     "montant": 1700},
    {"code": "LABO_INS_2H",       "libelle": "Insuline 2 Heures",                    "montant": 1700},
    {"code": "LABO_INS_JEUN",     "libelle": "Insuline à Jeun",                      "montant": 1700},
    {"code": "LABO_IONOGR",       "libelle": "Ionogramme",                            "montant": 3100},
    {"code": "LABO_KETO17",       "libelle": "Keto 17",                               "montant": 2600},
    {"code": "LABO_KOH",          "libelle": "KOH Mycose",                            "montant": 1400},
    {"code": "LABO_LAME_PER",     "libelle": "Lame Périphérique",                    "montant": 900},
    {"code": "LABO_LDH",          "libelle": "LDH",                                   "montant": 900},
    {"code": "LABO_LDL",          "libelle": "LDL",                                   "montant": 900},
    {"code": "LABO_LE_TEST",      "libelle": "Le Test",                               "montant": 900},
    {"code": "LABO_LEPTOSP",      "libelle": "Leptospira",                            "montant": 1600},
    {"code": "LABO_LH",           "libelle": "LH",                                    "montant": 1500},
    {"code": "LABO_LIPASE",       "libelle": "Lipase",                                "montant": 1400},
    {"code": "LABO_LIPIDES_T",    "libelle": "Lipides Totaux",                        "montant": 900},
    {"code": "LABO_LIQUIDE",      "libelle": "Liquide",                               "montant": 1400},
    {"code": "LABO_LIQ_CEPH",     "libelle": "Liquide Céphalo-Rachidien",            "montant": 1400},
    {"code": "LABO_LIQ_ASC",      "libelle": "Liquide d'Ascite",                     "montant": 1400},
    {"code": "LABO_LIQ_PLEUR",    "libelle": "Liquide Pleural",                      "montant": 1400},
    {"code": "LABO_LIQ_SYNO",     "libelle": "Liquide Synovial",                     "montant": 1400},
    {"code": "LABO_LITHIUM",      "libelle": "Lithium",                               "montant": 2100},
    {"code": "LABO_MAGNES",       "libelle": "Magnésium",                             "montant": 900},
    {"code": "LABO_MALARIA",      "libelle": "Malaria",                               "montant": 1100},
    {"code": "LABO_MANTOUX",      "libelle": "Mantoux Test (PPD)",                   "montant": 1500},
    {"code": "LABO_MARQUEURS",    "libelle": "Marqueurs Sériques Antigène Prostatique (Total et Libre)", "montant": 5900},
    {"code": "LABO_MICROALB",     "libelle": "Microalbumine",                         "montant": 900},
    {"code": "LABO_MONO_TEST",    "libelle": "Mono Test",                             "montant": 7200},
    {"code": "LABO_MSA",          "libelle": "MSA",                                   "montant": 5500},
    {"code": "LABO_NT_PRO",       "libelle": "NT-proBNP",                             "montant": 1700},
    {"code": "LABO_O_SULL",       "libelle": "O Sullivan Test",                       "montant": 23100},
    {"code": "LABO_PCR_COVID",    "libelle": "PCR COVID 19",                          "montant": 1400},
    {"code": "LABO_PHOS_AC",      "libelle": "Phosphatase Acide",                    "montant": 1600},
    {"code": "LABO_PHOS_AC_P",    "libelle": "Phosphatase Acide Prostatique",        "montant": 900},
    {"code": "LABO_PHOS_ALK",     "libelle": "Phosphatase Alcaline",                 "montant": 900},
    {"code": "LABO_PHOS_INORG",   "libelle": "Phosphore Inorganique",                "montant": 1400},
    {"code": "LABO_PHOS_U",       "libelle": "Phosphore Urinaire",                   "montant": 750},
    {"code": "LABO_PLAQUETTES",   "libelle": "Plaquettes",                            "montant": 1700},
    {"code": "LABO_PLOMB",        "libelle": "Plomb",                                 "montant": 1100},
    {"code": "LABO_POTASSIUM",    "libelle": "Potassium",                             "montant": 900},
    {"code": "LABO_POTASSIUM_U",  "libelle": "Potassium Urinaire",                   "montant": 5900},
    {"code": "LABO_PROCALC",      "libelle": "Procalcitonin",                         "montant": 2900},
    {"code": "LABO_PROFIL_CARD",  "libelle": "Profil Cardiaque",                     "montant": 2600},
    {"code": "LABO_PROFIL_HEP",   "libelle": "Profil Hépatique",                     "montant": 3400},
    {"code": "LABO_PROFIL_LIP",   "libelle": "Profil Lipidique",                     "montant": 2100},
    {"code": "LABO_PROFIL_THY1",  "libelle": "Profil Thyroïdien 1",                  "montant": 3400},
    {"code": "LABO_PROFIL_THY2",  "libelle": "Profil Thyroïdien II",                 "montant": 3900},
    {"code": "LABO_PROFIL_THY3",  "libelle": "Profil Thyroïdien III",                "montant": 2600},
    {"code": "LABO_PROFIL_THY4",  "libelle": "Profil Thyroïdien IV",                 "montant": 1600},
    {"code": "LABO_PROGEST",      "libelle": "Progestérone",                          "montant": 1600},
    {"code": "LABO_PROGEST_17",   "libelle": "Progestérone 17 OH",                   "montant": 1600},
    {"code": "LABO_PROLACT",      "libelle": "Prolactine",                            "montant": 1600},
    {"code": "LABO_PROT_BJ",      "libelle": "Protéines Bence Jones",                "montant": 900},
    {"code": "LABO_PROT_24H",     "libelle": "Protéines de 24 Heures",               "montant": 900},
    {"code": "LABO_PROT_SER",     "libelle": "Protéines Sériques",                   "montant": 900},
    {"code": "LABO_PROTHROM",     "libelle": "Prothrombine (PT)",                     "montant": 900},
    {"code": "LABO_PSA",          "libelle": "PSA",                                   "montant": 2000},
    {"code": "LABO_PTH",          "libelle": "PTH",                                   "montant": 1900},
    {"code": "LABO_RETYCU",       "libelle": "Rétyculocytes",                         "montant": 900},
    {"code": "LABO_RPR",          "libelle": "RPR",                                   "montant": 1000},
    {"code": "LABO_RUBELLA",      "libelle": "Rubella IgG",                           "montant": 2600},
    {"code": "LABO_SAT_TRANSF",   "libelle": "Saturation de la Transférine",         "montant": 900},
    {"code": "LABO_SCOTCH",       "libelle": "Scotch Tape Test",                      "montant": 900},
    {"code": "LABO_SELLES",       "libelle": "Selles",                                "montant": 1000},
    {"code": "LABO_SELLES_S",     "libelle": "Selles en Série",                      "montant": 1500},
    {"code": "LABO_SELLES_SO",    "libelle": "Selles / Sang Occulte",                "montant": 750},
    {"code": "LABO_SGOT",         "libelle": "SGOT/AST",                              "montant": 1000},
    {"code": "LABO_SGPT",         "libelle": "SGPT/ALT",                              "montant": 1000},
    {"code": "LABO_SICKLING",     "libelle": "Sickling Test",                         "montant": 750},
    {"code": "LABO_SODIUM",       "libelle": "Sodium",                                "montant": 900},
    {"code": "LABO_SODIUM_U",     "libelle": "Sodium Urinaire",                       "montant": 900},
    {"code": "LABO_SPERME",       "libelle": "Sperme",                                "montant": 900},
    {"code": "LABO_SUCRES_R",     "libelle": "Sucres Réducteurs",                    "montant": 700},
    {"code": "LABO_T3_LIBRE",     "libelle": "T3 Libre",                             "montant": 1400},
    {"code": "LABO_T3_TOTAL",     "libelle": "T3 Total",                             "montant": 1400},
    {"code": "LABO_T3_UPTAKE",    "libelle": "T3 Uptake",                            "montant": 900},
    {"code": "LABO_T4_LIBRE",     "libelle": "T4 Libre",                             "montant": 1400},
    {"code": "LABO_T4_TOTAL",     "libelle": "T4 Total",                             "montant": 900},
    {"code": "LABO_TC",           "libelle": "Temps de Coagulation (TC)",             "montant": 900},
    {"code": "LABO_TS",           "libelle": "Temps de Saignement (TS)",              "montant": 900},
    {"code": "LABO_TEST_GROSS",   "libelle": "Test de Grossesse",                    "montant": 900},
    {"code": "LABO_TESTOST",      "libelle": "Testostérone",                          "montant": 1600},
    {"code": "LABO_TESTOST_H",    "libelle": "Testostérone HRT H",                   "montant": 1600},
    {"code": "LABO_TESTOST_L",    "libelle": "Testostérone Libre",                   "montant": 1600},
    {"code": "LABO_THC_PCP",      "libelle": "THC ou PCP",                           "montant": 1600},
    {"code": "LABO_PTT",          "libelle": "Thromboplastine (PTT)",                 "montant": 900},
    {"code": "LABO_TIBC",         "libelle": "TIBC",                                  "montant": 900},
    {"code": "LABO_TORCH",        "libelle": "TORCH",                                 "montant": 8600},
    {"code": "LABO_TOXOPLASM",    "libelle": "Toxoplasmose IgG",                     "montant": 2600},
    {"code": "LABO_TP_PA",        "libelle": "TP-PA",                                 "montant": 2900},
    {"code": "LABO_TRIGLY",       "libelle": "Triglycérides",                         "montant": 900},
    {"code": "LABO_TROPONINE",    "libelle": "Troponine",                             "montant": 1400},
    {"code": "LABO_TROP_Q",       "libelle": "Troponine Quantitatif",                 "montant": 3000},
    {"code": "LABO_TSH",          "libelle": "TSH",                                   "montant": 1500},
    {"code": "LABO_TSH_AR",       "libelle": "TSH Anti-Récepteur",                   "montant": 3900},
    {"code": "LABO_TYPAGE_S",     "libelle": "Typage Sanguin (Groupe Sanguin)",       "montant": 900},
    {"code": "LABO_UREE",         "libelle": "Urée",                                  "montant": 900},
    {"code": "LABO_URINES",       "libelle": "Urines",                                "montant": 800},
    {"code": "LABO_VDRL",         "libelle": "VDRL (RPR)",                            "montant": 900},
    {"code": "LABO_VIT_B12",      "libelle": "Vitamine B12",                          "montant": 2900},
    {"code": "LABO_VIT_D",        "libelle": "Vitamine D",                            "montant": 3900},
    {"code": "LABO_VIT_1H",       "libelle": "Vitesse 1 Heure",                      "montant": 900},
    {"code": "LABO_VLDL",         "libelle": "VLDL",                                  "montant": 900},
    {"code": "LABO_VMA",          "libelle": "VMA",                                   "montant": 3000},
    {"code": "LABO_WESTERN",      "libelle": "Western Blot",                          "montant": 5900},
    {"code": "LABO_WIDAL",        "libelle": "Widal",                                 "montant": 1000},
]

# ── GESTES MÉDICAUX PAR SPÉCIALITÉ ────────────────────────────────────────────
# prix_fixe=False : prix libre saisi par caissier à l'acte
# prix_fixe=True  : prix fixe (dentisterie, labo)
GESTES_PAR_SPECIALITE = [
    # ── Orthopédie ────────────────────────────────────────────────────────────
    {"specialite": "Orthopédie", "libelle": "Pose de plâtre",                   "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Orthopédie", "libelle": "Infiltration articulaire",          "prix_suggere": 4000, "prix_fixe": False},
    {"specialite": "Orthopédie", "libelle": "Réduction fracture simple",         "prix_suggere": 5000, "prix_fixe": False},
    {"specialite": "Orthopédie", "libelle": "Ponction articulaire",              "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Orthopédie", "libelle": "Retrait plâtre",                   "prix_suggere": 1500, "prix_fixe": False},

    # ── Gynécologie ───────────────────────────────────────────────────────────
    {"specialite": "Gynécologie", "libelle": "Pose de DIU (stérilet)",           "prix_suggere": 5000, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Retrait DIU",                     "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Frottis cervico-vaginal",          "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Colposcopie",                     "prix_suggere": 4000, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Échographie obstétricale",         "prix_suggere": 3500, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Échographie pelvienne",            "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Gynécologie", "libelle": "Test de grossesse",               "prix_suggere": 900,  "prix_fixe": False},

    # ── Chirurgie Générale ───────────────────────────────────────────────────
    {"specialite": "Chirurgie Générale", "libelle": "Suture plaie simple",       "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Chirurgie Générale", "libelle": "Suture plaie complexe",     "prix_suggere": 5000, "prix_fixe": False},
    {"specialite": "Chirurgie Générale", "libelle": "Incision abcès",           "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Chirurgie Générale", "libelle": "Retrait fils",             "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Chirurgie Générale", "libelle": "Pansement complexe",        "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Chirurgie Générale", "libelle": "Biopsie",                  "prix_suggere": 5000, "prix_fixe": False},

    # ── Pédiatrie ─────────────────────────────────────────────────────────────
    {"specialite": "Pédiatrie", "libelle": "Injection IM enfant",               "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Pédiatrie", "libelle": "Perfusion IV enfant",               "prix_suggere": 2500, "prix_fixe": False},
    {"specialite": "Pédiatrie", "libelle": "Vaccination",                       "prix_suggere": 1500, "prix_fixe": False},

    # ── Médecine interne ──────────────────────────────────────────────────────
    {"specialite": "Médecine interne", "libelle": "Injection IM",               "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Médecine interne", "libelle": "Perfusion IV",               "prix_suggere": 2500, "prix_fixe": False},
    {"specialite": "Médecine interne", "libelle": "Pose de sonde urinaire",     "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Médecine interne", "libelle": "ECG (électrocardiogramme)",  "prix_suggere": 2000, "prix_fixe": False},

    # ── Neurologie / Neurochirurgie ───────────────────────────────────────────
    {"specialite": "Neurologie", "libelle": "Ponction lombaire",                "prix_suggere": 8000, "prix_fixe": False},
    {"specialite": "Neurologie", "libelle": "EEG (électroencéphalogramme)",     "prix_suggere": 5000, "prix_fixe": False},

    # ── ORL ───────────────────────────────────────────────────────────────────
    {"specialite": "ORL", "libelle": "Lavage d'oreille",                        "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "ORL", "libelle": "Nasofibroscopie",                        "prix_suggere": 4000, "prix_fixe": False},
    {"specialite": "ORL", "libelle": "Audiométrie",                            "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "ORL", "libelle": "Extraction corps étranger",              "prix_suggere": 3000, "prix_fixe": False},

    # ── Dermatologie ─────────────────────────────────────────────────────────
    {"specialite": "Dermatologie", "libelle": "Cryothérapie (azote liquide)",   "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Dermatologie", "libelle": "Exérèse lésion cutanée",        "prix_suggere": 5000, "prix_fixe": False},
    {"specialite": "Dermatologie", "libelle": "Biopsie cutanée",               "prix_suggere": 4000, "prix_fixe": False},

    # ── Cardiologie ───────────────────────────────────────────────────────────
    {"specialite": "Cardiologie", "libelle": "ECG (électrocardiogramme)",       "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Cardiologie", "libelle": "Échocardiographie",              "prix_suggere": 8000, "prix_fixe": False},
    {"specialite": "Cardiologie", "libelle": "Holter 24h",                     "prix_suggere": 10000,"prix_fixe": False},

    # ── Physiothérapie ───────────────────────────────────────────────────────
    {"specialite": "Physiothérapie", "libelle": "Séance rééducation (1 séance)","prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Physiothérapie", "libelle": "Ultrason thérapeutique",       "prix_suggere": 2500, "prix_fixe": False},
    {"specialite": "Physiothérapie", "libelle": "Électrostimulation",           "prix_suggere": 2500, "prix_fixe": False},
    {"specialite": "Physiothérapie", "libelle": "Massage thérapeutique",        "prix_suggere": 2000, "prix_fixe": False},

    # ── Optométrie ───────────────────────────────────────────────────────────
    {"specialite": "Optométrie", "libelle": "Examen de la vue complet",         "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Optométrie", "libelle": "Prescription lunettes",            "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Optométrie", "libelle": "Montures + verres (variable)",     "prix_suggere": 0,    "prix_fixe": False, "prix_min": 5000, "prix_max": 50000},

    # ── Gestes généraux (toutes spécialités) ─────────────────────────────────
    {"specialite": "Général", "libelle": "Injection intramusculaire (IM)",      "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Injection intraveineuse (IV)",        "prix_suggere": 2000, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Perfusion (avec soluté)",             "prix_suggere": 3000, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Pansement simple",                   "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Prise de sang",                      "prix_suggere": 500,  "prix_fixe": False},
    {"specialite": "Général", "libelle": "Pose de perfusion",                  "prix_suggere": 1500, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Observation (par jour)",             "prix_suggere": 5000, "prix_fixe": False},
    {"specialite": "Général", "libelle": "Garde de nuit",                      "prix_suggere": 8000, "prix_fixe": False},
]
